### ISSUE TITLE
Error initializing datadog on ios (expo eject project)

### ISSUE THREAD

**Issue by lurdharry** [DataDog/dd-sdk-reactnative#609] opened 2024-02-13 12:03 UTC
**Describe what happened**

**Steps to reproduce the issue:**

**Describe what you expected:**

**Additional context**

-   Version of the SDK:
-   Version of React Native:
-   `package.json`
-   `Podfile` and `Podfile.lock`
-   `android/build.gradle` and `android/app/build.gradle`

**Comment by louiszawadzki** [comment] 2024-02-13 13:05
Hi @lurdharry, I'm assuming this is a duplicate of https://github.com/DataDog/dd-sdk-reactnative/issues/610, so I'll close this issue. Feel free to reopen it if it isn't.

**Closed as completed by louiszawadzki** 2024-02-13 13:05 UTC
Labels: bug
