### ISSUE TITLE
Undefined symbols for architecture x86_64 (osx/ios)

### ISSUE THREAD

**Issue by WNemencha** [DataDog/dd-sdk-reactnative#41] opened 2021-04-20 11:39 UTC
Hello, DataDog team! :)

**Describe what happened:**
When trying to compile our app for iOS (react-native app), with freshly yarn added `dd-sdk-reactnative`, it fails with the following error:

```
Undefined symbols for architecture x86_64:
  "static Foundation.JSONEncoder.OutputFormatting.withoutEscapingSlashes.getter : Foundation.JSONEncoder.OutputFormatting", referenced from:
      static (extension in Datadog):Foundation.JSONEncoder.default() -> Foundation.JSONEncoder in libDatadogSDK.a(JSONEncoder.o)
  "Network.NWPath.isConstrained.getter : Swift.Bool", referenced from:
      closure #2 () -> Swift.Bool? in closure #1 (Network.NWPath) -> () in Datadog.NWPathNetworkConnectionInfoProvider.init(monitor: Network.NWPathMonitor) -> Datadog.NWPathNetworkConnectionInfoProvider in libDatadogSDK.a(NetworkConnectionInfoProvider.o)
  "(extension in Foundation):__C.NSFileHandle.readToEnd() throws -> Foundation.Data?", referenced from:
      Datadog.File.read() throws -> Foundation.Data in libDatadogSDK.a(File.o)
  "(extension in Foundation):__C.NSFileHandle.seekToEnd() throws -> Swift.UInt64", referenced from:
      Datadog.File.append(data: Foundation.Data) throws -> () in libDatadogSDK.a(File.o)
  "(extension in Foundation):__C.NSFileHandle.write<A where A: Foundation.DataProtocol>(contentsOf: A) throws -> ()", referenced from:
      Datadog.File.append(data: Foundation.Data) throws -> () in libDatadogSDK.a(File.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Steps to reproduce the issue:**

1. Install `dd-sdk-reactnative` in  a react-native v0.63.4 project (ios/android)
2. `cd ios/ && pod install`
3. `react-native run-ios`

**Describe what you expected:**

I expected the build to succeed, as the one for Android does.

**Additional context:**

- `"dd-sdk-reactnative": "^1.0.0-alpha5",`

**Comment by 0xnm** [comment] 2021-04-21 07:57
Hello @WNemencha! Can you please check if the same happens if you try to build our sample app on your machine? Also can you please tell which XCode version you are using?

**Comment by WNemencha** [comment] 2021-04-21 09:21
Hey @0xnm,

I've just tried to run your sample app and it seems to be compiling and running but I still can't receive any log inside my test DataDog account (in the RUM apps section).

I've been trying to fix this issue since yesterday and now that I think about it, it looks more like a Swift error to me, currently investigating ;)

**Comment by buranmert** [comment] 2021-04-23 16:17
hi @WNemencha 👋 
thanks for reporting the issue!
the issue seems to be caused by [a fix in React Native](https://github.com/facebook/react-native/pull/27922).
we raised https://github.com/facebook/react-native/pull/31417 to fix this in React Native template but this may take time.

### Problem

Swift frameworks can't be linked statically in pure Obj-C projects. React Native was keeping an empty `Swift.swift` file in its template project as a workaround, that makes it a Swift&Obj-C mixed target so that it works. the fix i mentioned above removed this file and set custom `Library Search Paths` for the compiler to find required Swift symbols during linking. however, it seems to be set to a wrong location and can't find some of the Swift symbols that our SDK relies on.

### Fix

please check that `Library Search Paths` in your `{MyApp}` project points to the following
```
LIBRARY_SEARCH_PATHS = (
  "\"$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)\"",
  "\"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)\"",
  "\"$(inherited)\"",
);
```
if so, can you please replace `$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)` with `/usr/lib/swift/` as seen in the screenshot below?

![Screenshot 2021-04-23 at 17 51 24](https://user-images.githubusercontent.com/1417500/115899752-6d727c80-a45f-11eb-9d34-34e6fda1ac2c.png)

let me know if that works (or not!) for you and/or if you have any other questions

**Comment by WNemencha** [comment] 2021-04-26 08:42
You know what ? It works! Thanks dear @buranmert, you saved the sprint :)

**Comment by buranmert** [comment] 2021-04-26 13:52
@WNemencha good news 👍 
i'm closing the issue as the issue is solved

**Closed by buranmert** 2021-04-26 13:52 UTC
Labels: awaiting-reply, bug

**Comment by papaschmidt** [comment] 2021-11-15 21:25
I have been getting the exact same issue.  While it will build after making the change listed in this issue, the app just closes out immediately afterwards when you attempt to load it.

`'/usr/local/lib/libswiftCore.dylib' (no such file), '/usr/lib/libswiftCore.dylib' (no such file)` from the Output

I've tried going to Build Settings in the target and changing `Always Embed Swift Standard Libraries` to `Yes`, but that doesn't seem to help here.  Any ideas what I need to do to get this working?

**Comment by buranmert** [comment] 2021-11-16 10:47
hi @papaschmidt 

i guess `Always Embed Swift Standard Libraries` shouldn't be needed as Swift libraries should already exist in iOS system images.

can you tell me which React Native, Xcode and iOS version you are using? 
does your project contain Swift code as well? 
has it ever worked before (e.g: with an older Datadog SDK or Xcode version) ?

**Comment by papaschmidt** [comment] 2021-11-16 14:27
Hello @buranmert ,

I am on the following:

react-native: 0.64.2
Xcode: Version 13.1 (13A1030d)
iOS: I am doing testing on 15.

We don't have any custom swift code that we wrote in this code base, however, some of our 3rd party libraries might have swift code.

This is our first attempt at integrating DataDog SDK into our project as we're looking to add it to our app for logging, so I haven't gotten it to work yet.   I did have to add a USER_DEFINED property `SWIFT_VERSION` to `5.0` to get it to install the pods, but I'm not sure if that is relevant to this.

**Comment by sregg** [comment] 2021-11-18 01:48
I thought this solution https://github.com/DataDog/dd-sdk-reactnative/issues/41#issuecomment-825766996 for me didn't work until I realized I was looking at my Target's Build Settings and not my App's.
Thought I'd share that if others make the same mistake.

**Comment by papaschmidt** [comment] 2021-11-19 21:05
Hello,

Our team was able to figure this out.  For anyone who runs into this issue in the future. You need to have a bridging header in your react-native project.  You just need to add an empty swift file to your project and during the process of it being added xCode will ask you if you want to create a bridging header - just click yes.

**Comment by quachdev** [comment] 2022-01-10 05:44
@papaschmidt I am running into this issue now. We have already created a bridging header in the project.

Is the current solution still to replace `$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)` with `/usr/lib/swift/`?

Ideally we don't have to change these settings as I have had bad experiences keeping track of these core changes for specific dependencies. What happens in the future if we were to bring on another dependency and it doesn't work because we replaced the default search path?

**Comment by buranmert** [comment] 2022-01-10 15:47
@quachdev `$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)` was introduced in React Native in order to solve the Swift-only libraries (e.g: Datadog iOS SDK) problem without a bridging header. However, it doesn't work as that path has the wrong set of symbols.
AFAIK the only way to solve this is changing it to `/usrl/lib/swift` as it seems to be what's actually needed.

we raised [a PR in React Native repo](https://github.com/facebook/react-native/pull/31417) to fix the issue for everyone but it didn't get enough attention unfortunately.

**Comment by rplankenhorn** [comment] 2022-08-08 18:29
FYI, the `LIBRARY_SEARCH_PATHS` fix doesn't appear to work with the latest versions of the packages:

```
"@datadog/mobile-react-native": "1.0.0",
 "@datadog/mobile-react-navigation": "1.0.0",
```

```
datadogSdkPath = resolve_transitive_dependency(__dir__, '@datadog/mobile-react-native')
pod 'DatadogSDKReactNative', :path => "#{datadogSdkPath}"
pod 'DatadogSDKBridge', '0.5.5'
pod 'DatadogSDK', '1.11.1'
```

**Comment by galdinoramon** [comment] 2025-01-15 15:47
I am still getting this error in compilation phase, even with the adjustments mentioned above. 

now I am in version 1.0.0-rc5 and any version above it I get this error. 

<img width="603" alt="Image" src="https://github.com/user-attachments/assets/90647479-21b6-4da6-a5e0-f9d64b828d89" />

"react-native": "0.72.5"

can anyone help me?
