### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by danReynolds** [DataDog/dd-sdk-reactnative#512] opened 2023-07-28 00:13 UTC
Getting this error on starting the library on 1.5.2 (tried 1.8.2) as well:

<img width="362" alt="Screenshot 2023-07-27 at 8 12 10 PM" src="https://github.com/DataDog/dd-sdk-reactnative/assets/2192930/f4a2fd80-3110-4282-8dec-ba49d9d055b3">

Looks like it's having issues parsing tokens in the /src folder. Is it expected that there should be a /src folder? Wonder why the token is invalid.

Was working fine on 1.0.0-rc5.

**Comment by louiszawadzki** [comment] 2023-07-28 12:43
Hi @danReynolds, thanks for reaching out!

It is indeed expected to have a `/src` folder.
From the looks of it, it looks as if something has changed a RegExp from our library. It is declared [here](https://github.com/DataDog/dd-sdk-reactnative/blob/develop/packages/core/src/rum/instrumentation/resourceTracking/requestProxy/XHRProxy/DatadogRumResource/internalDevResourceBlocklist.ts#L19) as such:

```javascript
const EXPO_DEV_LOGS_REGEX = new RegExp(
    '^http://((10|172|192).[0-9]+.[0-9]+.[0-9]+|localhost):[0-9]+/logs$'
);
```

Turning the string into a RegExp did not go right as it contains unescaped slashes.

Are you aware of anything in your app that would do such things? 
If not, could you include the following information to help us troubleshoot:
- a copy of your `package.json`
- a copy of your Babel config (probably in a `babel.config.js` or `.babelrc` file)

Thanks a lot!

**Comment by danReynolds** [comment] 2023-07-28 18:06
Yea so the source code you linked seems to show the same thing as my error right? The source code doesn't escape the slashes either? So are you saying that our transpilation should be escaping them or that something else is going on? Thanks!

**Comment by louiszawadzki** [comment] 2023-07-31 08:16
Hi @danReynolds,

Sorry my previous message was unclear, let me clarify.

Our code declares the regular expression using the `RegExp` constructor and a string, so there is no need to escape the slashes: 

```js
new RegExp(
    '^http://((10|172|192).[0-9]+.[0-9]+.[0-9]+|localhost):[0-9]+/logs$'
)
```

The message in your error has transformed this into a js RegExp (using `/`), but the slashes inside have not been escaped as they should have:

```js
/^http://((10|172|192).[0-9]+.[0-9]+.[0-9]+|localhost):[0-9]+/logs$/
```

As we cannot reproduce this on our end, this can be due to a combination of dependencies not doing the transpilation correctly. If you could include the following information, that would be really helpful:

- a copy of your `package.json`
- a copy of your Babel config (probably in a `babel.config.js` or `.babelrc` file)


Thanks a lot!

**Comment by louiszawadzki** [comment] 2024-03-04 09:54
Hi @danReynolds,

There has not been any activity on this issue for a while so I'm going to close it.

Feel free to reopen it with more details if you still encounter the problem :)

**Closed as completed by louiszawadzki** 2024-03-04 09:54 UTC
Labels: bug
