### ISSUE TITLE
Apple Privacy Manifest False Positives

### ISSUE THREAD

**Issue by ghost** [DataDog/dd-sdk-reactnative#650] opened 2024-04-09 20:42 UTC
### Describe the bug

There's no bug specifically in the react native sdk, but the following issues in the underlying iOS sdk are affecting react native applications that use it:
https://github.com/DataDog/dd-sdk-ios/issues/1749
https://github.com/DataDog/dd-sdk-ios/issues/1756

I'm opening this issue so that I can be notified when those issues are resolved, and a new version of this package is created which contains the fixes.

### Reproduction steps

N/A - see linked issues for the iOS SDK

### Affected SDK versions

2.2.0, most likely 2.3.1 but we haven't released with that version yet to know for sure

### Latest working SDK version

Unknown

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Integration Methods

Yarn

**Comment by marco-saia-datadog** [comment] 2024-04-17 13:46
Hey @bhandanyan-nomad, thank you for reaching out and opening this issue.

I am sorry you are experiencing this issue! We are aware of the cause, and it has high priority. 

As you mentioned, we are currently working on the fix, and the progress can be tracked on the following PRs:
 https://github.com/DataDog/dd-sdk-ios/issues/1749
https://github.com/DataDog/dd-sdk-ios/issues/1756

I will update you as soon as we start preparing the React Native SDK release, and I will link the PR to this thread.

**Comment by khaledmeltahan** [comment] 2024-05-01 08:38
Hey,@marco-saia-datadog, the issue was fixed and released as of [the DataDog-iOS 2.10.0 release](https://github.com/DataDog/dd-sdk-ios/releases/tag/2.10.0). Can you tell us more about your plans to release that to DataDog react native as well? As you're well aware, this is preventing us from releasing new app versions.

**Comment by marco-saia-datadog** [comment] 2024-05-13 10:49
Hey @khaledmeltahan, it is taking us some time to release RN with iOS v2.10.0, because the iOS update has a big impact on the RN side. I will keep you posted here!

**Comment by ghost** [comment] 2024-05-13 15:57
FWIW, we upgraded our project from react-native `0.71.16` -> `0.71.19` and were able to release a new version of our app after May 1st. The patches from RN included their own privacy manifest changes, which may overlap with datadogs and, for us, it seems like it did enough to remove all the warnings we were previously getting. If anyone is blocked, it is worth trying a patch upgrade on your current react-native version.

**Comment by marco-saia-datadog** [comment] 2024-07-05 09:41
@bhandanyan-nomad @khaledmeltahan 

Hello 👋 

We have released version [v2.4.0](https://github.com/DataDog/dd-sdk-reactnative/releases/tag/2.4.0) of the Datadog React Native SDK, which includes the update of the native DataDog SDKs and fixes the reported issue.

Feel free to re-open this or another issue if the problem persists.

Thank you for your patience 🙏

**Closed as completed by marco-saia-datadog** 2024-07-05 09:41 UTC
Labels: bug
