### ISSUE TITLE
Provide way to disable source map uploading with env var

### ISSUE THREAD

**Issue by justinadkins** [DataDog/dd-sdk-reactnative#547] opened 2023-10-30 16:40 UTC
**Is your feature request related to a problem? Please describe.**
We would like to take advantage of the automated source map uploading feature specified [here](https://docs.datadoghq.com/real_user_monitoring/error_tracking/reactnative/#upload-javascript-source-maps-on-android-builds) but only want source maps to be built during our CI runs. 

We often build APKs locally during development and in these cases we'd like the ability to disable source map uploads.

**Describe the solution you'd like**
I'd like an environment variable that could be used as a flag to disable source map uploads.

**Describe alternatives you've considered**
Alternatives would be to manually upload source maps in our CI pipeline but that defeats the purpose of using the automation currently available. We could also insert the line necessary for automation during CI but this will be bug prone and hide implementation details.

**Comment by louiszawadzki** [comment] 2023-10-30 17:02
Hi @justinadkins, thanks for reaching out!

Indeed we have a task in our backlog to enable all parameters of our `datadog-ci react-native` commands to be overridden by env variables, which could enable this feature by setting the `--dry-run` option locally.

In the meantime, I can suggest a few ways for you to achieve it while not altering your code in your CI.

### On iOS

Depending on your version of React Native, you will need to update either the `datadog-sourcemaps.sh` (if you have one) or directly the "Bundle React Native code and images" build phase in XCode.

You can change the line that executes `../node_modules/.bin/datadog-ci react-native xcode` to only execute if an env variable is set:

```bash
if [ -z "$UPLOAD_SOURCEMAPS" ]
then
      # Not uploading sourcemaps
      ../node_modules/react-native/scripts/react-native-xcode.sh
else
      # Uploading sourcemaps
      ../node_modules/.bin/datadog-ci react-native xcode
fi
```

And then set the `UPLOAD_SOURCEMAPS` variable in your CI.

### on Android

You can edit your `android/app/build.gradle` file to conditionally wrap the datadog sourcemaps upload plugin:

```groovy
if (System.getenv("UPLOAD_SOURCEMAPS")) {
    apply from: "../../node_modules/@datadog/mobile-react-native/datadog-sourcemaps.gradle"
} else {
    print("Not uploading sourcemaps to Datadog")
}
```
And then set the `UPLOAD_SOURCEMAPS` variable in your CI.

I know it's not ideal, but at least it's not logic hidden in the CI and you can re-enable it locally quickly if you need too.
Let me know if that unblocks you, I'll keep the issue open until we have better support for this

**Comment by justinadkins** [comment] 2023-10-30 17:07
Thank you @louiszawadzki!

**Comment by sciranka** [comment] 2023-11-02 09:56
Hi @louiszawadzki 
Thanks for the examples here, I have one question that is not clear to me and maybe we are doing something wrong.

I used the `datadog-react-native-wizard` to setup the uploading sourcemaps and dSym files.

I have the same issue in the local development that DATADOG_API_KEY is not set as ENV variable (because we don't want to expose it to all developers, so we are not using it locally, only in CI).

The weird thing:
A)
In the docs you are mentioning that uploading source maps are happening only for the `release` version of the app, but when I tried for Android, it was failing also when I tried to build debug version locally.

I was able to fix it with the suggested workaround above.

B)
When I try to build iOS version locally, there is no issue and I didn't use any workaround and didn't set any special ENV variable for this purpose, there is no error and I can build the debug app.

So my confusion is, whether I'm doing something wrong or it is something expected in the library?

Another not directly connected question is, is there any way we can check that the sourcemaps were uploaded? I tried to check documentation briefly, but didn't find any way how to check it.

Thank you very much,

Peter

**Comment by louiszawadzki** [comment] 2023-11-02 12:08
Hi @sciranka, thanks for reaching out!

The expected behaviour here is that we don't try to upload sourcemaps in debug mode, as described in the documentation.
However I wasn't able to reproduce the issue you described on Android, do you have the error message you were seeing and a reproducible example app you could share?

As for checking that sourcemaps were correctly uploaded the current best method is to trigger an error in your app and check that it is symbolicated correctly.
We are also currently working on displaying the list of uploaded sourcemaps so you can check more easily.

Let me know if you have any more questions!

**Comment by sciranka** [comment] 2023-11-02 12:21
@louiszawadzki  thank you for the prompt response.

Unfortunately, I don't have a reproducible example now, but if you are saying that it shouldn't try to upload the sourcemaps in debug mode, I will try to debug locally.

The error I get is
```
DATADOG_API_KEY environment variable not set
```

When I use your workaround, it skip the uploading part and it works as expected.

One note, that we have multiple flavors so when we are building the Android app locally, we are running
```
react-native run-android --mode=devDebug
```
But do not know whether it can be connected to the different flavors.

**Comment by louiszawadzki** [comment] 2023-11-02 13:02
Hi @sciranka, 

Thanks for coming back with this precision. Indeed the flavors are the root of the issue here.
On Android, we try to upload the sourcemaps whenever a js bundle is generated, regardless of whether the flavor contains "release" in its name.
I believe the workaround described above is currently the best way to prevent the upload of sourcemaps until we provide better support for Android flavors.

By the way, you can also package your app for your `devDebug` flavor instead of generating a bundle by specifying `debuggableVariants` in the `react {}` closure in your `android/app/build.gradle` file: https://reactnative.dev/docs/react-native-gradle-plugin#debuggablevariants.

Let me know if you have any more questions!

**Comment by sciranka** [comment] 2023-11-03 07:14
Hi @louiszawadzki 
Thank you very much, indeed I forgot to update `debuggableVariants`. After the update it works as expected.
Thank you very much.

**Comment by louiszawadzki** [comment] 2024-03-04 09:56
Hi @sciranka @justinadkins,

This issue seems solved so I'm going to close it.

Feel free to reopen it with more details if you still encounter any problem :)

**Closed as completed by louiszawadzki** 2024-03-04 09:56 UTC
Labels: enhancement
